export const EXAMPLES = [
  {
    title: 'Bouncing Ball',
    path: './examples/bouncing_ball.py',
    category: 'Mechanics',
    difficulty: 'Beginner',
    description: '중력과 반발 계수를 이용해 바닥에서 튀는 공을 시뮬레이션합니다.',
    preview: 'bounce',
  },
  {
    title: 'Projectile Motion',
    path: './examples/projectile_motion.py',
    category: 'Mechanics',
    difficulty: 'Beginner',
    description: '초기 속도와 중력으로 만들어지는 포물선 운동과 최근 궤적을 보여줍니다.',
    preview: 'projectile',
  },
  {
    title: 'Inclined Plane',
    path: './examples/inclined_plane.py',
    category: 'Mechanics',
    difficulty: 'Beginner',
    description: '공이 경사면을 따라 내려가는 운동을 단순화해 보여줍니다.',
    preview: 'projectile',
  },
  {
    title: 'Collision Lab',
    path: './examples/collision_lab.py',
    category: 'Mechanics',
    difficulty: 'Intermediate',
    description: '질량이 다른 두 공의 1차원 탄성 충돌을 관찰합니다.',
    preview: 'collision',
  },
  {
    title: 'Rolling Ball Track',
    path: './examples/rolling_ball_track.py',
    category: 'Mechanics',
    difficulty: 'Beginner',
    description: '트랙 위를 이동하는 공과 표식점으로 굴림 운동 느낌을 표현합니다.',
    preview: 'collision',
  },
  {
    title: 'Gas Box',
    path: './examples/gas_box.py',
    category: 'Mechanics',
    difficulty: 'Intermediate',
    description: '상자 안 입자들이 벽에 탄성 충돌하는 간단한 기체 운동 모델입니다.',
    preview: 'gas',
  },
  {
    title: 'Simple Harmonic Motion',
    path: './examples/simple_harmonic_motion.py',
    category: 'Oscillation',
    difficulty: 'Beginner',
    description: 'x = A cos(wt) 형태의 단순 조화 운동과 위치 표시점을 보여줍니다.',
    preview: 'spring',
  },
  {
    title: 'Damped Oscillator',
    path: './examples/damped_oscillator.py',
    category: 'Oscillation',
    difficulty: 'Beginner',
    description: '시간이 지날수록 진폭이 작아지는 감쇠 진동입니다.',
    preview: 'spring',
  },
  {
    title: 'Driven Oscillator',
    path: './examples/driven_oscillator.py',
    category: 'Oscillation',
    difficulty: 'Intermediate',
    description: '외부 구동점과 질량 사이의 위상 차이를 spring처럼 연결해 보여줍니다.',
    preview: 'spring',
  },
  {
    title: 'Spring Mass',
    path: './examples/spring_mass.py',
    category: 'Oscillation',
    difficulty: 'Intermediate',
    description: '여러 cylinder로 만든 스프링과 질량의 왕복 운동입니다.',
    preview: 'spring',
  },
  {
    title: 'Coupled Oscillators',
    path: './examples/coupled_oscillators.py',
    category: 'Oscillation',
    difficulty: 'Intermediate',
    description: '두 질량이 결합되어 서로 에너지를 주고받는 모양을 보여줍니다.',
    preview: 'spring',
  },
  {
    title: 'Double Pendulum',
    path: './examples/double_pendulum.py',
    category: 'Oscillation',
    difficulty: 'Intermediate',
    description: '두 막대와 질량으로 구성한 이중 진자 형태의 결합 진동입니다.',
    preview: 'pendulum',
  },
  {
    title: 'Bead on Hoop',
    path: './examples/bead_on_hoop.py',
    category: 'Oscillation',
    difficulty: 'Beginner',
    description: '원형 고리 위에서 구슬이 왕복하는 운동을 점 배열로 표현합니다.',
    preview: 'pendulum',
  },
  {
    title: 'Uniform Circular Motion',
    path: './examples/uniform_circular_motion.py',
    category: 'Rotation',
    difficulty: 'Beginner',
    description: '반지름 막대와 공이 일정한 각속도로 회전하는 원운동 예제입니다.',
    preview: 'orbit',
  },
  {
    title: 'Centripetal Force',
    path: './examples/centripetal_force.py',
    category: 'Rotation',
    difficulty: 'Intermediate',
    description: '회전하는 공에서 중심 방향으로 향하는 구심력 막대를 보여줍니다.',
    preview: 'orbit',
  },
  {
    title: 'Rotating Rods',
    path: './examples/rotating_rods.py',
    category: 'Rotation',
    difficulty: 'Beginner',
    description: '여러 막대가 중심에서 회전하며 axis 갱신을 보여주는 예제입니다.',
    preview: 'rods',
  },
  {
    title: 'Cylinder Axes',
    path: './examples/cylinder_axes.py',
    category: 'Geometry',
    difficulty: 'Beginner',
    description: 'cylinder의 pos, axis, radius 방향성을 빨강/초록/파랑 축으로 확인합니다.',
    preview: 'axes',
  },
  {
    title: 'Planet Orbit',
    path: './examples/planet_orbit.py',
    category: 'Gravity',
    difficulty: 'Intermediate',
    description: '중심 질량 주변을 도는 행성의 궤도 운동 예제입니다.',
    preview: 'orbit',
  },
  {
    title: 'Solar Mini System',
    path: './examples/solar_mini_system.py',
    category: 'Gravity',
    difficulty: 'Beginner',
    description: '세 행성이 서로 다른 속도로 태양 주위를 도는 미니 태양계입니다.',
    preview: 'solar',
  },
  {
    title: 'Two Body Gravity',
    path: './examples/two_body_gravity.py',
    category: 'Gravity',
    difficulty: 'Intermediate',
    description: '두 물체가 질량 중심 주위를 함께 도는 중력계 장면입니다.',
    preview: 'orbit',
  },
  {
    title: 'Binary Star',
    path: './examples/binary_star.py',
    category: 'Gravity',
    difficulty: 'Intermediate',
    description: '두 별과 작은 행성이 함께 도는 쌍성계 모델입니다.',
    preview: 'solar',
  },
  {
    title: 'Three Body Dance',
    path: './examples/three_body_dance.py',
    category: 'Gravity',
    difficulty: 'Intermediate',
    description: '세 물체가 같은 궤도를 위상 차이로 따라가는 라그랑주식 운동입니다.',
    preview: 'solar',
  },
  {
    title: 'Kepler Equal Areas',
    path: './examples/kepler_equal_areas.py',
    category: 'Gravity',
    difficulty: 'Intermediate',
    description: '가까울수록 빠르게 움직이는 타원 궤도로 케플러 법칙 느낌을 보여줍니다.',
    preview: 'orbit',
  },
  {
    title: 'Harmonic Wave',
    path: './examples/harmonic_wave.py',
    category: 'Waves',
    difficulty: 'Beginner',
    description: '줄 위의 입자들이 위아래로 흔들리며 진행파를 만듭니다.',
    preview: 'projectile',
  },
  {
    title: 'Standing Wave',
    path: './examples/standing_wave.py',
    category: 'Waves',
    difficulty: 'Beginner',
    description: '양끝은 거의 고정되고 가운데가 크게 흔들리는 정상파입니다.',
    preview: 'spring',
  },
  {
    title: 'Transverse Wave Chain',
    path: './examples/transverse_wave_chain.py',
    category: 'Waves',
    difficulty: 'Intermediate',
    description: '이웃 입자를 cylinder로 이어 움직이는 줄처럼 보이게 합니다.',
    preview: 'spring',
  },
  {
    title: 'Lattice Vibration',
    path: './examples/lattice_vibration.py',
    category: 'Waves',
    difficulty: 'Intermediate',
    description: '격자 원자들이 작은 진동을 하며 결정 진동을 흉내냅니다.',
    preview: 'gas',
  },
  {
    title: 'Electric Field Dipole',
    path: './examples/electric_field_dipole.py',
    category: 'Fields',
    difficulty: 'Intermediate',
    description: '+전하와 -전하 주변의 방향장을 작은 막대들로 표현합니다.',
    preview: 'axes',
  },
  {
    title: 'Magnetic Field Grid',
    path: './examples/magnetic_field_grid.py',
    category: 'Fields',
    difficulty: 'Beginner',
    description: '회전하는 작은 막대들이 공간의 자기장 방향처럼 움직입니다.',
    preview: 'rods',
  },
  {
    title: 'Charges Repulsion',
    path: './examples/charges_repulsion.py',
    category: 'Fields',
    difficulty: 'Intermediate',
    description: '같은 부호 전하 두 개가 서로 밀어내는 1차원 운동입니다.',
    preview: 'collision',
  },
];
